dist: bionic
language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"

before_install:
  - sudo apt update
  - sudo apt install nmap -y
  - pip install .

install:
  - pip install ".[test]"

script: 
  - pytest --cov
  - port-eye

after_success: 
  - if [[ $TRAVIS_PYTHON_VERSION == 3.7 ]]; then codecov; fi