dist: xenial
language: python
services:
   - docker

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - if [[ $TRAVIS_PYTHON_VERSION == 3.7 ]]; then docker build -t ahugues/port-eye .; fi
  - sudo apt update
  - sudo apt install nmap -y
  - pip install .

install:
  - pip install ".[test]"

script: 
  - pytest --cov
  - port-eye --help

after_success: 
  - if [[ $TRAVIS_PYTHON_VERSION == 3.7 ]]; then codecov; fi

deploy:
  - provider: pypi
    distributions: "sdist bdist_wheel"
    username: $PYPI_USERNAME
    password: $PYPI_PASSWORD
    on:
      tags: true
      python: 3.7
  - provider: script
    script: bash docker_push
    on:
      tags: true
      python: 3.7